//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    initializeSettings(): Promise<void> {
        let url_ = this.baseUrl + "/api/admin/initialize-settings";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processInitializeSettings(_response);
        });
    }

    protected processInitializeSettings(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    approveUser(body: ApproveUserRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/admin/approve-user";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processApproveUser(_response);
        });
    }

    protected processApproveUser(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    rejectUser(body: RejectUserRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/admin/reject-user";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRejectUser(_response);
        });
    }

    protected processRejectUser(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    settings(): Promise<ApplicationSettings> {
        let url_ = this.baseUrl + "/api/admin/settings";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSettings(_response);
        });
    }

    protected processSettings(response: Response): Promise<ApplicationSettings> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ApplicationSettings.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ApplicationSettings>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    editPOST(body: EditApplicationSettingsRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/admin/settings/edit";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processEditPOST(_response);
        });
    }

    protected processEditPOST(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    externalprojectAll(): Promise<ExternalProject[]> {
        let url_ = this.baseUrl + "/api/externalproject";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processExternalprojectAll(_response);
        });
    }

    protected processExternalprojectAll(response: Response): Promise<ExternalProject[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ExternalProject.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ExternalProject[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    externalprojectPOST(body: AddExternalProjectRequest | undefined): Promise<string> {
        let url_ = this.baseUrl + "/api/externalproject";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processExternalprojectPOST(_response);
        });
    }

    protected processExternalprojectPOST(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : null as any;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }

    /**
     * @return OK
     */
    externalprojectDELETE(projectKey: string): Promise<void> {
        let url_ = this.baseUrl + "/api/externalproject/{projectKey}";
        if (projectKey === undefined || projectKey === null)
            throw new globalThis.Error("The parameter 'projectKey' must be defined.");
        url_ = url_.replace("{projectKey}", encodeURIComponent("" + projectKey));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processExternalprojectDELETE(_response);
        });
    }

    protected processExternalprojectDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    file(rootDirectory: string): Promise<DirectoryContentsResponse> {
        let url_ = this.baseUrl + "/api/file/{rootDirectory}";
        if (rootDirectory === undefined || rootDirectory === null)
            throw new globalThis.Error("The parameter 'rootDirectory' must be defined.");
        url_ = url_.replace("{rootDirectory}", encodeURIComponent("" + rootDirectory));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processFile(_response);
        });
    }

    protected processFile(response: Response): Promise<DirectoryContentsResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DirectoryContentsResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<DirectoryContentsResponse>(null as any);
    }

    /**
     * @return OK
     */
    file2(rootDirectory: string, remainingPath: string): Promise<DirectoryContentsResponse> {
        let url_ = this.baseUrl + "/api/file/{rootDirectory}/{remainingPath}";
        if (rootDirectory === undefined || rootDirectory === null)
            throw new globalThis.Error("The parameter 'rootDirectory' must be defined.");
        url_ = url_.replace("{rootDirectory}", encodeURIComponent("" + rootDirectory));
        if (remainingPath === undefined || remainingPath === null)
            throw new globalThis.Error("The parameter 'remainingPath' must be defined.");
        url_ = url_.replace("{remainingPath}", encodeURIComponent("" + remainingPath));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processFile2(_response);
        });
    }

    protected processFile2(response: Response): Promise<DirectoryContentsResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DirectoryContentsResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<DirectoryContentsResponse>(null as any);
    }

    /**
     * @return OK
     */
    rootDirectory(): Promise<string[]> {
        let url_ = this.baseUrl + "/api/file/root-directory";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRootDirectory(_response);
        });
    }

    protected processRootDirectory(response: Response): Promise<string[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(item);
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string[]>(null as any);
    }

    /**
     * @return OK
     */
    download(rootDirectory: string, filePath: string): Promise<void> {
        let url_ = this.baseUrl + "/api/file/download/{rootDirectory}/{filePath}";
        if (rootDirectory === undefined || rootDirectory === null)
            throw new globalThis.Error("The parameter 'rootDirectory' must be defined.");
        url_ = url_.replace("{rootDirectory}", encodeURIComponent("" + rootDirectory));
        if (filePath === undefined || filePath === null)
            throw new globalThis.Error("The parameter 'filePath' must be defined.");
        url_ = url_.replace("{filePath}", encodeURIComponent("" + filePath));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDownload(_response);
        });
    }

    protected processDownload(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    downloadZip(body: DownloadFilesAsZipRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/file/download-zip";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDownloadZip(_response);
        });
    }

    protected processDownloadZip(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    register(body: RegisterNewUserRequest | undefined): Promise<string> {
        let url_ = this.baseUrl + "/api/user/register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRegister(_response);
        });
    }

    protected processRegister(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : null as any;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    login(body: LoginRequest | undefined): Promise<LoginResponse> {
        let url_ = this.baseUrl + "/api/user/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: Response): Promise<LoginResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = LoginResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LoginResponse>(null as any);
    }

    /**
     * @return OK
     */
    all(): Promise<RegisteredUser[]> {
        let url_ = this.baseUrl + "/api/user/all";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAll(_response);
        });
    }

    protected processAll(response: Response): Promise<RegisteredUser[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(RegisteredUser.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RegisteredUser[]>(null as any);
    }

    /**
     * @return OK
     */
    user(userKey: string): Promise<RegisteredUser> {
        let url_ = this.baseUrl + "/api/user/{userKey}";
        if (userKey === undefined || userKey === null)
            throw new globalThis.Error("The parameter 'userKey' must be defined.");
        url_ = url_.replace("{userKey}", encodeURIComponent("" + userKey));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUser(_response);
        });
    }

    protected processUser(response: Response): Promise<RegisteredUser> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = RegisteredUser.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RegisteredUser>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    editPUT(body: EditUserRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/user/edit";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processEditPUT(_response);
        });
    }

    protected processEditPUT(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class AddExternalProjectRequest implements IAddExternalProjectRequest {
    projectName?: string | null;
    projectUri?: string | null;
    tooltip?: string | null;

    constructor(data?: IAddExternalProjectRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.projectName = _data["projectName"] !== undefined ? _data["projectName"] : null as any;
            this.projectUri = _data["projectUri"] !== undefined ? _data["projectUri"] : null as any;
            this.tooltip = _data["tooltip"] !== undefined ? _data["tooltip"] : null as any;
        }
    }

    static fromJS(data: any): AddExternalProjectRequest {
        data = typeof data === 'object' ? data : {};
        let result = new AddExternalProjectRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["projectName"] = this.projectName !== undefined ? this.projectName : null as any;
        data["projectUri"] = this.projectUri !== undefined ? this.projectUri : null as any;
        data["tooltip"] = this.tooltip !== undefined ? this.tooltip : null as any;
        return data;
    }
}

export interface IAddExternalProjectRequest {
    projectName?: string | null;
    projectUri?: string | null;
    tooltip?: string | null;
}

export class ApplicationSettings implements IApplicationSettings {
    key?: string;
    editingToken?: string | null;
    downloadPaths?: DirectoryConfiguration[] | null;

    constructor(data?: IApplicationSettings) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.key = _data["key"] !== undefined ? _data["key"] : null as any;
            this.editingToken = _data["editingToken"] !== undefined ? _data["editingToken"] : null as any;
            if (Array.isArray(_data["downloadPaths"])) {
                this.downloadPaths = [] as any;
                for (let item of _data["downloadPaths"])
                    this.downloadPaths!.push(DirectoryConfiguration.fromJS(item));
            }
            else {
                this.downloadPaths = null as any;
            }
        }
    }

    static fromJS(data: any): ApplicationSettings {
        data = typeof data === 'object' ? data : {};
        let result = new ApplicationSettings();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["key"] = this.key !== undefined ? this.key : null as any;
        data["editingToken"] = this.editingToken !== undefined ? this.editingToken : null as any;
        if (Array.isArray(this.downloadPaths)) {
            data["downloadPaths"] = [];
            for (let item of this.downloadPaths)
                data["downloadPaths"].push(item ? item.toJSON() : null as any);
        }
        return data;
    }
}

export interface IApplicationSettings {
    key?: string;
    editingToken?: string | null;
    downloadPaths?: DirectoryConfiguration[] | null;
}

export class ApproveUserRequest implements IApproveUserRequest {
    requestedUserKey?: string;

    constructor(data?: IApproveUserRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.requestedUserKey = _data["requestedUserKey"] !== undefined ? _data["requestedUserKey"] : null as any;
        }
    }

    static fromJS(data: any): ApproveUserRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ApproveUserRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["requestedUserKey"] = this.requestedUserKey !== undefined ? this.requestedUserKey : null as any;
        return data;
    }
}

export interface IApproveUserRequest {
    requestedUserKey?: string;
}

export class DirectoryConfiguration implements IDirectoryConfiguration {
    path?: string | null;
    alias?: string | null;

    constructor(data?: IDirectoryConfiguration) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.path = _data["path"] !== undefined ? _data["path"] : null as any;
            this.alias = _data["alias"] !== undefined ? _data["alias"] : null as any;
        }
    }

    static fromJS(data: any): DirectoryConfiguration {
        data = typeof data === 'object' ? data : {};
        let result = new DirectoryConfiguration();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["path"] = this.path !== undefined ? this.path : null as any;
        data["alias"] = this.alias !== undefined ? this.alias : null as any;
        return data;
    }
}

export interface IDirectoryConfiguration {
    path?: string | null;
    alias?: string | null;
}

export class DirectoryContentsResponse implements IDirectoryContentsResponse {
    directories?: string[] | null;
    files?: string[] | null;

    constructor(data?: IDirectoryContentsResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["directories"])) {
                this.directories = [] as any;
                for (let item of _data["directories"])
                    this.directories!.push(item);
            }
            else {
                this.directories = null as any;
            }
            if (Array.isArray(_data["files"])) {
                this.files = [] as any;
                for (let item of _data["files"])
                    this.files!.push(item);
            }
            else {
                this.files = null as any;
            }
        }
    }

    static fromJS(data: any): DirectoryContentsResponse {
        data = typeof data === 'object' ? data : {};
        let result = new DirectoryContentsResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.directories)) {
            data["directories"] = [];
            for (let item of this.directories)
                data["directories"].push(item);
        }
        if (Array.isArray(this.files)) {
            data["files"] = [];
            for (let item of this.files)
                data["files"].push(item);
        }
        return data;
    }
}

export interface IDirectoryContentsResponse {
    directories?: string[] | null;
    files?: string[] | null;
}

export class DownloadFilesAsZipRequest implements IDownloadFilesAsZipRequest {
    rootDirectory?: string | null;
    filePaths?: string[] | null;

    constructor(data?: IDownloadFilesAsZipRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.rootDirectory = _data["rootDirectory"] !== undefined ? _data["rootDirectory"] : null as any;
            if (Array.isArray(_data["filePaths"])) {
                this.filePaths = [] as any;
                for (let item of _data["filePaths"])
                    this.filePaths!.push(item);
            }
            else {
                this.filePaths = null as any;
            }
        }
    }

    static fromJS(data: any): DownloadFilesAsZipRequest {
        data = typeof data === 'object' ? data : {};
        let result = new DownloadFilesAsZipRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["rootDirectory"] = this.rootDirectory !== undefined ? this.rootDirectory : null as any;
        if (Array.isArray(this.filePaths)) {
            data["filePaths"] = [];
            for (let item of this.filePaths)
                data["filePaths"].push(item);
        }
        return data;
    }
}

export interface IDownloadFilesAsZipRequest {
    rootDirectory?: string | null;
    filePaths?: string[] | null;
}

export class EditApplicationSettingsRequest implements IEditApplicationSettingsRequest {
    directoryConfigurations?: DirectoryConfiguration[] | null;

    constructor(data?: IEditApplicationSettingsRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["directoryConfigurations"])) {
                this.directoryConfigurations = [] as any;
                for (let item of _data["directoryConfigurations"])
                    this.directoryConfigurations!.push(DirectoryConfiguration.fromJS(item));
            }
            else {
                this.directoryConfigurations = null as any;
            }
        }
    }

    static fromJS(data: any): EditApplicationSettingsRequest {
        data = typeof data === 'object' ? data : {};
        let result = new EditApplicationSettingsRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.directoryConfigurations)) {
            data["directoryConfigurations"] = [];
            for (let item of this.directoryConfigurations)
                data["directoryConfigurations"].push(item ? item.toJSON() : null as any);
        }
        return data;
    }
}

export interface IEditApplicationSettingsRequest {
    directoryConfigurations?: DirectoryConfiguration[] | null;
}

export class EditUserRequest implements IEditUserRequest {
    userToEditKey?: string;
    firstName?: string | null;
    lastName?: string | null;
    passwordRaw?: string | null;
    status?: UserStatus;

    constructor(data?: IEditUserRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userToEditKey = _data["userToEditKey"] !== undefined ? _data["userToEditKey"] : null as any;
            this.firstName = _data["firstName"] !== undefined ? _data["firstName"] : null as any;
            this.lastName = _data["lastName"] !== undefined ? _data["lastName"] : null as any;
            this.passwordRaw = _data["passwordRaw"] !== undefined ? _data["passwordRaw"] : null as any;
            this.status = _data["status"] !== undefined ? _data["status"] : null as any;
        }
    }

    static fromJS(data: any): EditUserRequest {
        data = typeof data === 'object' ? data : {};
        let result = new EditUserRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userToEditKey"] = this.userToEditKey !== undefined ? this.userToEditKey : null as any;
        data["firstName"] = this.firstName !== undefined ? this.firstName : null as any;
        data["lastName"] = this.lastName !== undefined ? this.lastName : null as any;
        data["passwordRaw"] = this.passwordRaw !== undefined ? this.passwordRaw : null as any;
        data["status"] = this.status !== undefined ? this.status : null as any;
        return data;
    }
}

export interface IEditUserRequest {
    userToEditKey?: string;
    firstName?: string | null;
    lastName?: string | null;
    passwordRaw?: string | null;
    status?: UserStatus;
}

export class ExternalProject implements IExternalProject {
    key?: string;
    editingToken?: string | null;
    projectName?: string | null;
    projectUri?: string | null;
    tooltip?: string | null;

    constructor(data?: IExternalProject) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.key = _data["key"] !== undefined ? _data["key"] : null as any;
            this.editingToken = _data["editingToken"] !== undefined ? _data["editingToken"] : null as any;
            this.projectName = _data["projectName"] !== undefined ? _data["projectName"] : null as any;
            this.projectUri = _data["projectUri"] !== undefined ? _data["projectUri"] : null as any;
            this.tooltip = _data["tooltip"] !== undefined ? _data["tooltip"] : null as any;
        }
    }

    static fromJS(data: any): ExternalProject {
        data = typeof data === 'object' ? data : {};
        let result = new ExternalProject();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["key"] = this.key !== undefined ? this.key : null as any;
        data["editingToken"] = this.editingToken !== undefined ? this.editingToken : null as any;
        data["projectName"] = this.projectName !== undefined ? this.projectName : null as any;
        data["projectUri"] = this.projectUri !== undefined ? this.projectUri : null as any;
        data["tooltip"] = this.tooltip !== undefined ? this.tooltip : null as any;
        return data;
    }
}

export interface IExternalProject {
    key?: string;
    editingToken?: string | null;
    projectName?: string | null;
    projectUri?: string | null;
    tooltip?: string | null;
}

export class HashedString implements IHashedString {
    value?: string | null;

    constructor(data?: IHashedString) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.value = _data["value"] !== undefined ? _data["value"] : null as any;
        }
    }

    static fromJS(data: any): HashedString {
        data = typeof data === 'object' ? data : {};
        let result = new HashedString();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["value"] = this.value !== undefined ? this.value : null as any;
        return data;
    }
}

export interface IHashedString {
    value?: string | null;
}

export class LoginRequest implements ILoginRequest {
    firstName?: string | null;
    lastName?: string | null;
    passwordRaw?: string | null;

    constructor(data?: ILoginRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.firstName = _data["firstName"] !== undefined ? _data["firstName"] : null as any;
            this.lastName = _data["lastName"] !== undefined ? _data["lastName"] : null as any;
            this.passwordRaw = _data["passwordRaw"] !== undefined ? _data["passwordRaw"] : null as any;
        }
    }

    static fromJS(data: any): LoginRequest {
        data = typeof data === 'object' ? data : {};
        let result = new LoginRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["firstName"] = this.firstName !== undefined ? this.firstName : null as any;
        data["lastName"] = this.lastName !== undefined ? this.lastName : null as any;
        data["passwordRaw"] = this.passwordRaw !== undefined ? this.passwordRaw : null as any;
        return data;
    }
}

export interface ILoginRequest {
    firstName?: string | null;
    lastName?: string | null;
    passwordRaw?: string | null;
}

export class LoginResponse implements ILoginResponse {
    token?: string | null;
    userKey?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    displayName?: string | null;
    status?: UserStatus;

    constructor(data?: ILoginResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.token = _data["token"] !== undefined ? _data["token"] : null as any;
            this.userKey = _data["userKey"] !== undefined ? _data["userKey"] : null as any;
            this.firstName = _data["firstName"] !== undefined ? _data["firstName"] : null as any;
            this.lastName = _data["lastName"] !== undefined ? _data["lastName"] : null as any;
            this.displayName = _data["displayName"] !== undefined ? _data["displayName"] : null as any;
            this.status = _data["status"] !== undefined ? _data["status"] : null as any;
        }
    }

    static fromJS(data: any): LoginResponse {
        data = typeof data === 'object' ? data : {};
        let result = new LoginResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["token"] = this.token !== undefined ? this.token : null as any;
        data["userKey"] = this.userKey !== undefined ? this.userKey : null as any;
        data["firstName"] = this.firstName !== undefined ? this.firstName : null as any;
        data["lastName"] = this.lastName !== undefined ? this.lastName : null as any;
        data["displayName"] = this.displayName !== undefined ? this.displayName : null as any;
        data["status"] = this.status !== undefined ? this.status : null as any;
        return data;
    }
}

export interface ILoginResponse {
    token?: string | null;
    userKey?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    displayName?: string | null;
    status?: UserStatus;
}

export class RegisterNewUserRequest implements IRegisterNewUserRequest {
    firstName?: string | null;
    lastName?: string | null;
    passwordRaw?: string | null;

    constructor(data?: IRegisterNewUserRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.firstName = _data["firstName"] !== undefined ? _data["firstName"] : null as any;
            this.lastName = _data["lastName"] !== undefined ? _data["lastName"] : null as any;
            this.passwordRaw = _data["passwordRaw"] !== undefined ? _data["passwordRaw"] : null as any;
        }
    }

    static fromJS(data: any): RegisterNewUserRequest {
        data = typeof data === 'object' ? data : {};
        let result = new RegisterNewUserRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["firstName"] = this.firstName !== undefined ? this.firstName : null as any;
        data["lastName"] = this.lastName !== undefined ? this.lastName : null as any;
        data["passwordRaw"] = this.passwordRaw !== undefined ? this.passwordRaw : null as any;
        return data;
    }
}

export interface IRegisterNewUserRequest {
    firstName?: string | null;
    lastName?: string | null;
    passwordRaw?: string | null;
}

export class RegisteredUser implements IRegisteredUser {
    key?: string;
    editingToken?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    readonly displayName?: string | null;
    passwordHash?: HashedString;
    status?: UserStatus;
    creationDate?: Date;
    lastLoginDate?: Date;

    constructor(data?: IRegisteredUser) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.key = _data["key"] !== undefined ? _data["key"] : null as any;
            this.editingToken = _data["editingToken"] !== undefined ? _data["editingToken"] : null as any;
            this.firstName = _data["firstName"] !== undefined ? _data["firstName"] : null as any;
            this.lastName = _data["lastName"] !== undefined ? _data["lastName"] : null as any;
            (this as any).displayName = _data["displayName"] !== undefined ? _data["displayName"] : null as any;
            this.passwordHash = _data["passwordHash"] ? HashedString.fromJS(_data["passwordHash"]) : null as any;
            this.status = _data["status"] !== undefined ? _data["status"] : null as any;
            this.creationDate = _data["creationDate"] ? new Date(_data["creationDate"].toString()) : null as any;
            this.lastLoginDate = _data["lastLoginDate"] ? new Date(_data["lastLoginDate"].toString()) : null as any;
        }
    }

    static fromJS(data: any): RegisteredUser {
        data = typeof data === 'object' ? data : {};
        let result = new RegisteredUser();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["key"] = this.key !== undefined ? this.key : null as any;
        data["editingToken"] = this.editingToken !== undefined ? this.editingToken : null as any;
        data["firstName"] = this.firstName !== undefined ? this.firstName : null as any;
        data["lastName"] = this.lastName !== undefined ? this.lastName : null as any;
        data["displayName"] = this.displayName !== undefined ? this.displayName : null as any;
        data["passwordHash"] = this.passwordHash ? this.passwordHash.toJSON() : null as any;
        data["status"] = this.status !== undefined ? this.status : null as any;
        data["creationDate"] = this.creationDate ? this.creationDate.toISOString() : null as any;
        data["lastLoginDate"] = this.lastLoginDate ? this.lastLoginDate.toISOString() : null as any;
        return data;
    }
}

export interface IRegisteredUser {
    key?: string;
    editingToken?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    displayName?: string | null;
    passwordHash?: HashedString;
    status?: UserStatus;
    creationDate?: Date;
    lastLoginDate?: Date;
}

export class RejectUserRequest implements IRejectUserRequest {
    requestedUserKey?: string;

    constructor(data?: IRejectUserRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.requestedUserKey = _data["requestedUserKey"] !== undefined ? _data["requestedUserKey"] : null as any;
        }
    }

    static fromJS(data: any): RejectUserRequest {
        data = typeof data === 'object' ? data : {};
        let result = new RejectUserRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["requestedUserKey"] = this.requestedUserKey !== undefined ? this.requestedUserKey : null as any;
        return data;
    }
}

export interface IRejectUserRequest {
    requestedUserKey?: string;
}

export enum UserStatus {
    Unknown = "Unknown",
    Inactive = "Inactive",
    Unapproved = "Unapproved",
    Approved = "Approved",
    Rejected = "Rejected",
    Admin = "Admin",
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    throw new ApiException(message, status, response, headers, result);
}