//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    create(body: CreateNewProjectRequest | undefined): Promise<string> {
        let url_ = this.baseUrl + "/api/project/projects/create";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : null as any;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }

    /**
     * @return OK
     */
    projectsAll(): Promise<Project[]> {
        let url_ = this.baseUrl + "/api/project/projects";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processProjectsAll(_response);
        });
    }

    protected processProjectsAll(response: Response): Promise<Project[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(Project.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Project[]>(null as any);
    }

    /**
     * @return OK
     */
    projects(projectShorthand: string): Promise<Project> {
        let url_ = this.baseUrl + "/api/project/projects/{projectShorthand}";
        if (projectShorthand === undefined || projectShorthand === null)
            throw new globalThis.Error("The parameter 'projectShorthand' must be defined.");
        url_ = url_.replace("{projectShorthand}", encodeURIComponent("" + projectShorthand));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processProjects(_response);
        });
    }

    protected processProjects(response: Response): Promise<Project> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = Project.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Project>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    createTicket(projectShorthand: string, body: CreateTicketRequest | undefined): Promise<Project> {
        let url_ = this.baseUrl + "/api/project/projects/{projectShorthand}/create-ticket";
        if (projectShorthand === undefined || projectShorthand === null)
            throw new globalThis.Error("The parameter 'projectShorthand' must be defined.");
        url_ = url_.replace("{projectShorthand}", encodeURIComponent("" + projectShorthand));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateTicket(_response);
        });
    }

    protected processCreateTicket(response: Response): Promise<Project> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = Project.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Project>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    addComment(body: AddCommentToTicketRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/project/ticket/add-comment";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAddComment(_response);
        });
    }

    protected processAddComment(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    edit(body: EditTicketRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/project/ticket/edit";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processEdit(_response);
        });
    }

    protected processEdit(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    register(body: RegisterNewUserRequest | undefined): Promise<string> {
        let url_ = this.baseUrl + "/api/user/register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRegister(_response);
        });
    }

    protected processRegister(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : null as any;
    
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    login(body: LoginRequest | undefined): Promise<LoginResponse> {
        let url_ = this.baseUrl + "/api/user/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: Response): Promise<LoginResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = LoginResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LoginResponse>(null as any);
    }

    /**
     * @return OK
     */
    user(userKey: string): Promise<RegisteredUser> {
        let url_ = this.baseUrl + "/api/user/user/{userKey}";
        if (userKey === undefined || userKey === null)
            throw new globalThis.Error("The parameter 'userKey' must be defined.");
        url_ = url_.replace("{userKey}", encodeURIComponent("" + userKey));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUser(_response);
        });
    }

    protected processUser(response: Response): Promise<RegisteredUser> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = RegisteredUser.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RegisteredUser>(null as any);
    }
}

export class AddCommentToTicketRequest implements IAddCommentToTicketRequest {
    projectKey?: string;
    ticketIndex?: number;
    comment?: string | null;

    constructor(data?: IAddCommentToTicketRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.projectKey = _data["projectKey"] !== undefined ? _data["projectKey"] : null as any;
            this.ticketIndex = _data["ticketIndex"] !== undefined ? _data["ticketIndex"] : null as any;
            this.comment = _data["comment"] !== undefined ? _data["comment"] : null as any;
        }
    }

    static fromJS(data: any): AddCommentToTicketRequest {
        data = typeof data === 'object' ? data : {};
        let result = new AddCommentToTicketRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["projectKey"] = this.projectKey !== undefined ? this.projectKey : null as any;
        data["ticketIndex"] = this.ticketIndex !== undefined ? this.ticketIndex : null as any;
        data["comment"] = this.comment !== undefined ? this.comment : null as any;
        return data;
    }
}

export interface IAddCommentToTicketRequest {
    projectKey?: string;
    ticketIndex?: number;
    comment?: string | null;
}

export class Comment implements IComment {
    value?: string | null;
    author?: string;
    createdDate?: Date;

    constructor(data?: IComment) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.value = _data["value"] !== undefined ? _data["value"] : null as any;
            this.author = _data["author"] !== undefined ? _data["author"] : null as any;
            this.createdDate = _data["createdDate"] ? new Date(_data["createdDate"].toString()) : null as any;
        }
    }

    static fromJS(data: any): Comment {
        data = typeof data === 'object' ? data : {};
        let result = new Comment();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["value"] = this.value !== undefined ? this.value : null as any;
        data["author"] = this.author !== undefined ? this.author : null as any;
        data["createdDate"] = this.createdDate ? this.createdDate.toISOString() : null as any;
        return data;
    }
}

export interface IComment {
    value?: string | null;
    author?: string;
    createdDate?: Date;
}

export class CreateNewProjectRequest implements ICreateNewProjectRequest {
    projectName?: string | null;
    projectShorthand?: string | null;
    projectDescription?: string | null;

    constructor(data?: ICreateNewProjectRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.projectName = _data["projectName"] !== undefined ? _data["projectName"] : null as any;
            this.projectShorthand = _data["projectShorthand"] !== undefined ? _data["projectShorthand"] : null as any;
            this.projectDescription = _data["projectDescription"] !== undefined ? _data["projectDescription"] : null as any;
        }
    }

    static fromJS(data: any): CreateNewProjectRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateNewProjectRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["projectName"] = this.projectName !== undefined ? this.projectName : null as any;
        data["projectShorthand"] = this.projectShorthand !== undefined ? this.projectShorthand : null as any;
        data["projectDescription"] = this.projectDescription !== undefined ? this.projectDescription : null as any;
        return data;
    }
}

export interface ICreateNewProjectRequest {
    projectName?: string | null;
    projectShorthand?: string | null;
    projectDescription?: string | null;
}

export class CreateTicketRequest implements ICreateTicketRequest {
    title?: string | null;
    description?: string | null;
    labels?: string[] | null;

    constructor(data?: ICreateTicketRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.title = _data["title"] !== undefined ? _data["title"] : null as any;
            this.description = _data["description"] !== undefined ? _data["description"] : null as any;
            if (Array.isArray(_data["labels"])) {
                this.labels = [] as any;
                for (let item of _data["labels"])
                    this.labels!.push(item);
            }
            else {
                this.labels = null as any;
            }
        }
    }

    static fromJS(data: any): CreateTicketRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateTicketRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title !== undefined ? this.title : null as any;
        data["description"] = this.description !== undefined ? this.description : null as any;
        if (Array.isArray(this.labels)) {
            data["labels"] = [];
            for (let item of this.labels)
                data["labels"].push(item);
        }
        return data;
    }
}

export interface ICreateTicketRequest {
    title?: string | null;
    description?: string | null;
    labels?: string[] | null;
}

export class EditTicketRequest implements IEditTicketRequest {
    projectKey?: string;
    ticketIndex?: number;
    title?: string | null;
    description?: string | null;
    labels?: string[] | null;
    status?: TicketStatus;

    constructor(data?: IEditTicketRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.projectKey = _data["projectKey"] !== undefined ? _data["projectKey"] : null as any;
            this.ticketIndex = _data["ticketIndex"] !== undefined ? _data["ticketIndex"] : null as any;
            this.title = _data["title"] !== undefined ? _data["title"] : null as any;
            this.description = _data["description"] !== undefined ? _data["description"] : null as any;
            if (Array.isArray(_data["labels"])) {
                this.labels = [] as any;
                for (let item of _data["labels"])
                    this.labels!.push(item);
            }
            else {
                this.labels = null as any;
            }
            this.status = _data["status"] !== undefined ? _data["status"] : null as any;
        }
    }

    static fromJS(data: any): EditTicketRequest {
        data = typeof data === 'object' ? data : {};
        let result = new EditTicketRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["projectKey"] = this.projectKey !== undefined ? this.projectKey : null as any;
        data["ticketIndex"] = this.ticketIndex !== undefined ? this.ticketIndex : null as any;
        data["title"] = this.title !== undefined ? this.title : null as any;
        data["description"] = this.description !== undefined ? this.description : null as any;
        if (Array.isArray(this.labels)) {
            data["labels"] = [];
            for (let item of this.labels)
                data["labels"].push(item);
        }
        data["status"] = this.status !== undefined ? this.status : null as any;
        return data;
    }
}

export interface IEditTicketRequest {
    projectKey?: string;
    ticketIndex?: number;
    title?: string | null;
    description?: string | null;
    labels?: string[] | null;
    status?: TicketStatus;
}

export class LoginRequest implements ILoginRequest {
    username?: string | null;
    passwordRaw?: string | null;

    constructor(data?: ILoginRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.username = _data["username"] !== undefined ? _data["username"] : null as any;
            this.passwordRaw = _data["passwordRaw"] !== undefined ? _data["passwordRaw"] : null as any;
        }
    }

    static fromJS(data: any): LoginRequest {
        data = typeof data === 'object' ? data : {};
        let result = new LoginRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["username"] = this.username !== undefined ? this.username : null as any;
        data["passwordRaw"] = this.passwordRaw !== undefined ? this.passwordRaw : null as any;
        return data;
    }
}

export interface ILoginRequest {
    username?: string | null;
    passwordRaw?: string | null;
}

export class LoginResponse implements ILoginResponse {
    token?: string | null;
    userKey?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    username?: string | null;
    role?: Role;

    constructor(data?: ILoginResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.token = _data["token"] !== undefined ? _data["token"] : null as any;
            this.userKey = _data["userKey"] !== undefined ? _data["userKey"] : null as any;
            this.firstName = _data["firstName"] !== undefined ? _data["firstName"] : null as any;
            this.lastName = _data["lastName"] !== undefined ? _data["lastName"] : null as any;
            this.username = _data["username"] !== undefined ? _data["username"] : null as any;
            this.role = _data["role"] !== undefined ? _data["role"] : null as any;
        }
    }

    static fromJS(data: any): LoginResponse {
        data = typeof data === 'object' ? data : {};
        let result = new LoginResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["token"] = this.token !== undefined ? this.token : null as any;
        data["userKey"] = this.userKey !== undefined ? this.userKey : null as any;
        data["firstName"] = this.firstName !== undefined ? this.firstName : null as any;
        data["lastName"] = this.lastName !== undefined ? this.lastName : null as any;
        data["username"] = this.username !== undefined ? this.username : null as any;
        data["role"] = this.role !== undefined ? this.role : null as any;
        return data;
    }
}

export interface ILoginResponse {
    token?: string | null;
    userKey?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    username?: string | null;
    role?: Role;
}

export class Project implements IProject {
    key?: string;
    editingToken?: string | null;
    name?: string | null;
    shorthand?: string | null;
    description?: string | null;
    defaultTicketStatus?: TicketStatus;
    allowedUserKeys?: string[] | null;
    creatorKey?: string;
    status?: ProjectStatus;
    tickets?: Ticket[] | null;
    labels?: string[] | null;

    constructor(data?: IProject) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.key = _data["key"] !== undefined ? _data["key"] : null as any;
            this.editingToken = _data["editingToken"] !== undefined ? _data["editingToken"] : null as any;
            this.name = _data["name"] !== undefined ? _data["name"] : null as any;
            this.shorthand = _data["shorthand"] !== undefined ? _data["shorthand"] : null as any;
            this.description = _data["description"] !== undefined ? _data["description"] : null as any;
            this.defaultTicketStatus = _data["defaultTicketStatus"] !== undefined ? _data["defaultTicketStatus"] : null as any;
            if (Array.isArray(_data["allowedUserKeys"])) {
                this.allowedUserKeys = [] as any;
                for (let item of _data["allowedUserKeys"])
                    this.allowedUserKeys!.push(item);
            }
            else {
                this.allowedUserKeys = null as any;
            }
            this.creatorKey = _data["creatorKey"] !== undefined ? _data["creatorKey"] : null as any;
            this.status = _data["status"] !== undefined ? _data["status"] : null as any;
            if (Array.isArray(_data["tickets"])) {
                this.tickets = [] as any;
                for (let item of _data["tickets"])
                    this.tickets!.push(Ticket.fromJS(item));
            }
            else {
                this.tickets = null as any;
            }
            if (Array.isArray(_data["labels"])) {
                this.labels = [] as any;
                for (let item of _data["labels"])
                    this.labels!.push(item);
            }
            else {
                this.labels = null as any;
            }
        }
    }

    static fromJS(data: any): Project {
        data = typeof data === 'object' ? data : {};
        let result = new Project();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["key"] = this.key !== undefined ? this.key : null as any;
        data["editingToken"] = this.editingToken !== undefined ? this.editingToken : null as any;
        data["name"] = this.name !== undefined ? this.name : null as any;
        data["shorthand"] = this.shorthand !== undefined ? this.shorthand : null as any;
        data["description"] = this.description !== undefined ? this.description : null as any;
        data["defaultTicketStatus"] = this.defaultTicketStatus !== undefined ? this.defaultTicketStatus : null as any;
        if (Array.isArray(this.allowedUserKeys)) {
            data["allowedUserKeys"] = [];
            for (let item of this.allowedUserKeys)
                data["allowedUserKeys"].push(item);
        }
        data["creatorKey"] = this.creatorKey !== undefined ? this.creatorKey : null as any;
        data["status"] = this.status !== undefined ? this.status : null as any;
        if (Array.isArray(this.tickets)) {
            data["tickets"] = [];
            for (let item of this.tickets)
                data["tickets"].push(item ? item.toJSON() : null as any);
        }
        if (Array.isArray(this.labels)) {
            data["labels"] = [];
            for (let item of this.labels)
                data["labels"].push(item);
        }
        return data;
    }
}

export interface IProject {
    key?: string;
    editingToken?: string | null;
    name?: string | null;
    shorthand?: string | null;
    description?: string | null;
    defaultTicketStatus?: TicketStatus;
    allowedUserKeys?: string[] | null;
    creatorKey?: string;
    status?: ProjectStatus;
    tickets?: Ticket[] | null;
    labels?: string[] | null;
}

export enum ProjectStatus {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
}

export class RegisterNewUserRequest implements IRegisterNewUserRequest {
    firstName?: string | null;
    lastName?: string | null;
    username?: string | null;
    passwordRaw?: string | null;

    constructor(data?: IRegisterNewUserRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.firstName = _data["firstName"] !== undefined ? _data["firstName"] : null as any;
            this.lastName = _data["lastName"] !== undefined ? _data["lastName"] : null as any;
            this.username = _data["username"] !== undefined ? _data["username"] : null as any;
            this.passwordRaw = _data["passwordRaw"] !== undefined ? _data["passwordRaw"] : null as any;
        }
    }

    static fromJS(data: any): RegisterNewUserRequest {
        data = typeof data === 'object' ? data : {};
        let result = new RegisterNewUserRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["firstName"] = this.firstName !== undefined ? this.firstName : null as any;
        data["lastName"] = this.lastName !== undefined ? this.lastName : null as any;
        data["username"] = this.username !== undefined ? this.username : null as any;
        data["passwordRaw"] = this.passwordRaw !== undefined ? this.passwordRaw : null as any;
        return data;
    }
}

export interface IRegisterNewUserRequest {
    firstName?: string | null;
    lastName?: string | null;
    username?: string | null;
    passwordRaw?: string | null;
}

export class RegisteredUser implements IRegisteredUser {
    key?: string;
    editingToken?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    username?: string | null;
    passwordHash?: string | null;
    creationDate?: Date;
    lastLoginDate?: Date;
    role?: Role;

    constructor(data?: IRegisteredUser) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.key = _data["key"] !== undefined ? _data["key"] : null as any;
            this.editingToken = _data["editingToken"] !== undefined ? _data["editingToken"] : null as any;
            this.firstName = _data["firstName"] !== undefined ? _data["firstName"] : null as any;
            this.lastName = _data["lastName"] !== undefined ? _data["lastName"] : null as any;
            this.username = _data["username"] !== undefined ? _data["username"] : null as any;
            this.passwordHash = _data["passwordHash"] !== undefined ? _data["passwordHash"] : null as any;
            this.creationDate = _data["creationDate"] ? new Date(_data["creationDate"].toString()) : null as any;
            this.lastLoginDate = _data["lastLoginDate"] ? new Date(_data["lastLoginDate"].toString()) : null as any;
            this.role = _data["role"] !== undefined ? _data["role"] : null as any;
        }
    }

    static fromJS(data: any): RegisteredUser {
        data = typeof data === 'object' ? data : {};
        let result = new RegisteredUser();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["key"] = this.key !== undefined ? this.key : null as any;
        data["editingToken"] = this.editingToken !== undefined ? this.editingToken : null as any;
        data["firstName"] = this.firstName !== undefined ? this.firstName : null as any;
        data["lastName"] = this.lastName !== undefined ? this.lastName : null as any;
        data["username"] = this.username !== undefined ? this.username : null as any;
        data["passwordHash"] = this.passwordHash !== undefined ? this.passwordHash : null as any;
        data["creationDate"] = this.creationDate ? this.creationDate.toISOString() : null as any;
        data["lastLoginDate"] = this.lastLoginDate ? this.lastLoginDate.toISOString() : null as any;
        data["role"] = this.role !== undefined ? this.role : null as any;
        return data;
    }
}

export interface IRegisteredUser {
    key?: string;
    editingToken?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    username?: string | null;
    passwordHash?: string | null;
    creationDate?: Date;
    lastLoginDate?: Date;
    role?: Role;
}

export enum Role {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
}

export class Ticket implements ITicket {
    index?: number;
    title?: string | null;
    description?: string | null;
    assignedToKey?: string;
    reporterKey?: string;
    comments?: Comment[] | null;
    createdDate?: Date;
    completedDate?: Date;
    labels?: string[] | null;
    status?: TicketStatus;

    constructor(data?: ITicket) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.index = _data["index"] !== undefined ? _data["index"] : null as any;
            this.title = _data["title"] !== undefined ? _data["title"] : null as any;
            this.description = _data["description"] !== undefined ? _data["description"] : null as any;
            this.assignedToKey = _data["assignedToKey"] !== undefined ? _data["assignedToKey"] : null as any;
            this.reporterKey = _data["reporterKey"] !== undefined ? _data["reporterKey"] : null as any;
            if (Array.isArray(_data["comments"])) {
                this.comments = [] as any;
                for (let item of _data["comments"])
                    this.comments!.push(Comment.fromJS(item));
            }
            else {
                this.comments = null as any;
            }
            this.createdDate = _data["createdDate"] ? new Date(_data["createdDate"].toString()) : null as any;
            this.completedDate = _data["completedDate"] ? new Date(_data["completedDate"].toString()) : null as any;
            if (Array.isArray(_data["labels"])) {
                this.labels = [] as any;
                for (let item of _data["labels"])
                    this.labels!.push(item);
            }
            else {
                this.labels = null as any;
            }
            this.status = _data["status"] !== undefined ? _data["status"] : null as any;
        }
    }

    static fromJS(data: any): Ticket {
        data = typeof data === 'object' ? data : {};
        let result = new Ticket();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["index"] = this.index !== undefined ? this.index : null as any;
        data["title"] = this.title !== undefined ? this.title : null as any;
        data["description"] = this.description !== undefined ? this.description : null as any;
        data["assignedToKey"] = this.assignedToKey !== undefined ? this.assignedToKey : null as any;
        data["reporterKey"] = this.reporterKey !== undefined ? this.reporterKey : null as any;
        if (Array.isArray(this.comments)) {
            data["comments"] = [];
            for (let item of this.comments)
                data["comments"].push(item ? item.toJSON() : null as any);
        }
        data["createdDate"] = this.createdDate ? this.createdDate.toISOString() : null as any;
        data["completedDate"] = this.completedDate ? this.completedDate.toISOString() : null as any;
        if (Array.isArray(this.labels)) {
            data["labels"] = [];
            for (let item of this.labels)
                data["labels"].push(item);
        }
        data["status"] = this.status !== undefined ? this.status : null as any;
        return data;
    }
}

export interface ITicket {
    index?: number;
    title?: string | null;
    description?: string | null;
    assignedToKey?: string;
    reporterKey?: string;
    comments?: Comment[] | null;
    createdDate?: Date;
    completedDate?: Date;
    labels?: string[] | null;
    status?: TicketStatus;
}

export enum TicketStatus {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
    _5 = 5,
}

export class ZincApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isZincApiException = true;

    static isZincApiException(obj: any): obj is ZincApiException {
        return obj.isZincApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    throw new ZincApiException(message, status, response, headers, result);
}